CREATE TABLE brands
(
    id                    bigint generated by default as identity not null primary key,
    customer_phone_number varchar(50) unique                      not null,
    first_name            VARCHAR(100),
    last_name             VARCHAR(100),
    count_ball            INTEGER,
    count_like            BIGINT,
    tariff_id             BIGINT,
    telegram_nick         VARCHAR(255),
    birth_date            DATE,
    position              VARCHAR(255),
    discussion_topics     TEXT,
    public_speaking_willingness VARCHAR(255),
    entrepreneur_community VARCHAR(255),
    brand_name            VARCHAR(255),
    business_category     VARCHAR(255),
    brand_type            VARCHAR(50),
    branded_social_link   VARCHAR(255),
    brand_website_link    VARCHAR(255),
    followers_count       BIGINT,
    average_check         BIGINT,
    product_uniqueness    TEXT,
    customer_problem_solved TEXT,
    interaction_formats   TEXT,
    collaboration_goal    TEXT,
    preferred_business_category VARCHAR(255),
    brand_presence_territory VARCHAR(255),
    business_essence      TEXT,
    brand_values          TEXT,
    target_audience_description TEXT,
    target_audience_categories TEXT,
    foreign key (customer_phone_number) references customers (phone_number)
);

COMMENT ON TABLE brands IS 'Таблица для хранения карточки бренда';
COMMENT ON COLUMN brands.id IS 'Первичный ключ таблицы';
COMMENT ON COLUMN brands.customer_phone_number IS 'Внешний ключ на customers';
COMMENT ON COLUMN brands.count_ball IS 'Количество баллов, набранных брендом';
COMMENT ON COLUMN brands.count_like IS 'Количество лайков, полученных брендом';
COMMENT ON COLUMN brands.tariff_id IS 'Ссылка на тариф, который использует бренд';
COMMENT ON COLUMN brands.telegram_nick IS 'Никнейм в Telegram';
COMMENT ON COLUMN brands.birth_date IS 'Дата рождения';
COMMENT ON COLUMN brands.position IS 'Должность';
COMMENT ON COLUMN brands.discussion_topics IS 'Темы для обсуждения или рекомендации';
COMMENT ON COLUMN brands.public_speaking_willingness IS 'Готовность к публичным выступлениям';
COMMENT ON COLUMN brands.entrepreneur_community IS 'Название или ссылка на сообщество предпринимателей';
COMMENT ON COLUMN brands.brand_name IS 'Название бренда';
COMMENT ON COLUMN brands.business_category IS 'Категория бизнеса';
COMMENT ON COLUMN brands.brand_type IS 'Тип бренда (онлайн/оффлайн)';
COMMENT ON COLUMN brands.branded_social_link IS 'Ссылка на страницу бренда соц. сети';
COMMENT ON COLUMN brands.brand_website_link IS 'Ссылка на сайт бренда или маркетплейс';
COMMENT ON COLUMN brands.followers_count IS 'Количество подписчиков';
COMMENT ON COLUMN brands.average_check IS 'Средний чек';
COMMENT ON COLUMN brands.product_uniqueness IS 'Уникальность продукта';
COMMENT ON COLUMN brands.customer_problem_solved IS 'Проблема, решаемая для клиента';
COMMENT ON COLUMN brands.interaction_formats IS 'Форматы взаимодействия';
COMMENT ON COLUMN brands.collaboration_goal IS 'Цель коллаборации';
COMMENT ON COLUMN brands.preferred_business_category IS 'Предпочитаемая категория для коллаборации';
COMMENT ON COLUMN brands.brand_presence_territory IS 'Территория представленности бренда';
COMMENT ON COLUMN brands.business_essence IS 'Суть и ключевая миссия бизнеса';
COMMENT ON COLUMN brands.brand_values IS 'Ключевые ценности бренда';
COMMENT ON COLUMN brands.target_audience_description IS 'Описание целевой аудитории';
COMMENT ON COLUMN brands.target_audience_categories IS 'Категории целевой аудитории';

