create table brands
(
    id                          bigint generated by default as identity not null primary key,
    customer_phone_number       varchar(50) unique                      not null,
    name                        varchar(255)                            not null,
    tariff_plan_id              bigint,
    count_ball                  integer,
    count_like                  integer,
    telegram_nickname           varchar(255),
    birth_date                  date,
    position                    varchar(255),
    discussion_topics           text,
    public_speaking_willingness varchar(255),
    entrepreneur_community      varchar(255),
    business_category           varchar(255),
    brand_type                  varchar(50),
    branded_social_link         varchar(255),
    brand_website_link          varchar(255),
    followers_count             integer,
    average_check               integer,
    product_uniqueness          text,
    customer_problem_solved     text,
    interaction_formats         text,
    collaboration_goal          text,
    preferred_business_category varchar(255),
    brand_presence_territory    varchar(255),
    business_essence            text,
    brand_values                text,
    target_audience_description text,
    target_audience_categories  text,
    foreign key (customer_phone_number) references customers (phone_number),
    foreign key (tariff_plan_id) references tariff_plan (id)
);
comment on table brands is 'Таблица для хранения карточки бренда';
comment on column brands.id is 'Первичный ключ таблицы';
comment on column brands.customer_phone_number is 'Внешний ключ на customers';
comment on column brands.name is 'Название бренда';
comment on column brands.tariff_plan_id is 'Ссылка на тариф, который использует бренд';
comment on column brands.count_ball is 'Количество баллов, набранных брендом';
comment on column brands.count_like is 'Количество лайков, полученных брендом';
comment on column brands.telegram_nickname is 'Никнейм в Telegram';
comment on column brands.birth_date is 'Дата рождения';
comment on column brands.position is 'Должность';
comment on column brands.discussion_topics is 'Темы для обсуждения или рекомендации';
comment on column brands.public_speaking_willingness is 'Готовность к публичным выступлениям';
comment on column brands.entrepreneur_community is 'Название или ссылка на сообщество предпринимателей';
comment on column brands.business_category is 'Категория бизнеса';
comment on column brands.brand_type is 'Тип бренда (онлайн/оффлайн)';
comment on column brands.branded_social_link is 'Ссылка на страницу бренда соц. сети';
comment on column brands.brand_website_link is 'Ссылка на сайт бренда или маркетплейс';
comment on column brands.followers_count is 'Количество подписчиков';
comment on column brands.average_check is 'Средний чек';
comment on column brands.product_uniqueness is 'Уникальность продукта';
comment on column brands.customer_problem_solved is 'Проблема, решаемая для клиента';
comment on column brands.interaction_formats is 'Форматы взаимодействия';
comment on column brands.collaboration_goal is 'Цель коллаборации';
comment on column brands.preferred_business_category is 'Предпочитаемая категория для коллаборации';
comment on column brands.brand_presence_territory is 'Территория представленности бренда';
comment on column brands.business_essence is 'Суть и ключевая миссия бизнеса';
comment on column brands.brand_values is 'Ключевые ценности бренда';
comment on column brands.target_audience_description is 'Описание целевой аудитории';
comment on column brands.target_audience_categories is 'Категории целевой аудитории';


