create table chat_rooms
(
    id bigint generated by default as identity not null primary key,
    phone_number1 varchar(50) not null,
    phone_number2 varchar(50) not null,
    room_name varchar(50) not null,
    foreign key (phone_number1) references customers (phone_number),
    foreign key (phone_number2) references customers (phone_number),
    unique (phone_number1, phone_number2)
);
comment on table chat_rooms is 'Таблица для комнат чата';
comment on column chat_rooms.id is 'Первичный ключ таблицы';
comment on column chat_rooms.phone_number1 is 'Первый участник чата';
comment on column chat_rooms.phone_number2 is 'Второй участник чата';
comment on column chat_rooms.room_name is 'Название комнаты';

create table chat_message
(
    id bigint generated by default as identity not null primary key,
    chat_room_id bigint,
    sender_phone_number varchar(50) not null,
    content varchar(1000) not null,
    status varchar(20) not null,
    created_at timestamp not null,
    foreign key (chat_room_id) references chat_rooms (id),
    foreign key (sender_phone_number) references customers (phone_number)
);

comment on table chat_message is 'Таблица хранения сообщений чата';
comment on column chat_message.id is 'Первичный ключ таблицы';
comment on column chat_message.chat_room_id is 'Внешний ключ на chat_rooms';
comment on column chat_message.sender_phone_number is 'Внешний ключ на customers - отправитель сообщения';
comment on column chat_message.content is 'Содержимое сообщения';
comment on column chat_message.status is 'Статус сообщения: SENT, DELIVERED, READ';
comment on column chat_message.created_at is 'timestamp отправки сообщения';

