create table images
(
    id         bigint generated by default as identity not null primary key,
    brand_id   bigint                                  not null,
    filename   varchar(255)                            not null,
    image_type varchar(255)                            not null,
    foreign key (brand_id) references brands (id)
);
comment on table images is 'Таблица для картинок бренда';
comment on column images.id is 'Первичный ключ таблицы';
comment on column images.brand_id is 'Внешний ключ на brands';
comment on column images.filename is 'Имя файла картинки';
comment on column images.image_type is 'Тип картинки logo, profile, brand';
