###

# @name send file
# @no-log
POST https://dipdeepcode.ru/api/files
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< D:\files\image.png

###
# @name get file
# @no-log
@filename = MjQvMmYvNDkvc3NpaWRtYWdlLnBuZw==
GET https://dipdeepcode.ru/api/files?filename={{filename}}




